### ISSUE TITLE
CC 2015 not compatible

### ISSUE THREAD

**Issue by crookookoo** [chrometaphore/ink#1]

**Comment by chrometaphore** [comment]
I will extend support to Photoshop CC2015 after figuring out how to pull out data for multiple FX and Artboards.

**Comment by bmathews** [comment]
@chrometaphore Are you working on this and/or are you accepting PRs?

**Comment by chrometaphore** [comment]
Ink is now available for Photoshop cc2015 with a limited set of features. Still working on this on my spare time :)

**Comment by chrometaphore** [comment]
@bmathews PRs are more than welcome!
